travis:
  secure:
    BINSTAR_TOKEN: Ok5dAULDig8v9e3sGNG3vzc7mo4l2LVGq6B6NCp6ZhkIMKl+lKGc12GEg7GYKsIV1AL081lnpCtonVkuhldcwsfT+k4cV92NiYvAiiQfG7XLQwm75ES45q5KoZWdBNnOkx8O/+pcBLoTscejQNO4lcy35zTSmk+R3sIWAgubYyMyLpj0kdRJ9gbjxokcitKe3GEaM6y2/PzId7twOP+OmhTGZsi0N/SSq2Qfk6bdKrB39tT3CKz+pyy1caqzUqXowhxIjUYpjw31gwqO//CJ+jk2PnHnG3fwEcgw+9qOGNBBIrTzyXJaqWgX8iPoX+qn3pTKn6yFT2xqF3gJ3buZY80AjH7eiwVCg2BiFsPXFuSkwIwGAGYW4q24kWrTLQ+sNTwUV4bFDIKUsgw3rYmbPUga5lu8wxtDRNx7AxrpQjvOjz1ZKGfA9Uxd38f4Sdyid+VB/6j7FPHwLIVZqXJfdz4rn9G5S0Je991LSjMBV1wtlfkdIeejjyY5mnk8NcBQDTTD3YNuW5nIYYGUmwx2m3JEj4r4cHmf+OcdmOITCazIzYq6KbeOBVx/GN4FcDAcf310gMRYgacXzNddrsxXskPxf9KDr9Oh8V6qJrra+Wq/P8x91r0KWdUfZPOSUdeSzvjzP9iAZuCmgAT/3oGRufBhe7MrMraIoC76MEPDGpo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
